### ISSUE TITLE
NetworkOnMainThreadException when unsubscribing

### ISSUE THREAD

**Issue by nairbspace** [jacek-marchwicki/JavaWebsocketClient#21]
Seeing some crash reports from users with stacktrace below. Odd because I thought this issue was fixed awhile back with OkHttp. Might be due to the fact that OkHttp-ws is still experimental.

This problem can be solved by setting `unsubcribeOn()` to a background thread for meantime. 

```
Fatal Exception: java.lang.RuntimeException: Unable to pause activity: android.os.NetworkOnMainThreadException
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4379)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4338)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4313)
       at android.app.ActivityThread.access$1200(ActivityThread.java:197)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1692)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6872)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by android.os.NetworkOnMainThreadException
       at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
       at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:855)
       at okio.Okio$1.write(Okio.java:80)
       at okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
       at okio.RealBufferedSink.emit(RealBufferedSink.java:183)
       at okhttp3.internal.ws.WebSocketWriter.writeControlFrameSynchronized(WebSocketWriter.java:152)
       at okhttp3.internal.ws.WebSocketWriter.writeClose(WebSocketWriter.java:111)
       at okhttp3.internal.ws.RealWebSocket.close(RealWebSocket.java:168)
       at com.appunite.websocket.rx.RxWebSockets$LockingWebSocket.close(RxWebSockets.java:209)
       at com.appunite.websocket.rx.RxWebSockets$1$2.call(RxWebSockets.java:163)
       at rx.subscriptions.BooleanSubscription.unsubscribe(BooleanSubscription.java:71)
       at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:124)
       at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:113)
       at rx.Subscriber.unsubscribe(Subscriber.java:98)
       at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:124)
       at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:113)
       at rx.Subscriber.unsubscribe(Subscriber.java:98)
       at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:124)
       at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:113)
       at rx.Subscriber.unsubscribe(Subscriber.java:98)
       at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:124)
       at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:113)
       at rx.Subscriber.unsubscribe(Subscriber.java:98)
       at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:124)
       at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:113)
       at rx.Subscriber.unsubscribe(Subscriber.java:98)
       at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:124)
       at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:113)
       at rx.Subscriber.unsubscribe(Subscriber.java:98)
       at rx.subscriptions.SerialSubscription.unsubscribe(SerialSubscription.java:66)
       at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:124)
       at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:113)
       at rx.Subscriber.unsubscribe(Subscriber.java:98)
       at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:124)
       at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:113)
       at rx.Subscriber.unsubscribe(Subscriber.java:98)
       at com.domain.interactor.UseCase.unsubscribe(UseCase.java:36)
       at com.ui.playback.PlaybackPresenter.onPause(PlaybackPresenter.java:61)
       at com.ui.templates.BaseFragmentListener.onPause(BaseFragmentListener.java:80)
       at android.support.v4.app.Fragment.performPause(Fragment.java:2139)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1117)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
       at android.support.v4.app.FragmentManagerImpl.dispatchPause(FragmentManager.java:2060)
       at android.support.v4.app.FragmentController.dispatchPause(FragmentController.java:207)
       at android.support.v4.app.FragmentActivity.onPause(FragmentActivity.java:443)
       at com.ui.templates.BaseActivity.onPause(BaseActivity.java:47)
       at android.app.Activity.performPause(Activity.java:6706)
       at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1324)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4365)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4338)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4313)
       at android.app.ActivityThread.access$1200(ActivityThread.java:197)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1692)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6872)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by jacek-marchwicki** [comment]
This is not a bug, just graceful disconnecting. Unsubscribing send message via websocket (look here: https://tools.ietf.org/html/rfc6455#section-7.1.1) so it shouln't be done on main thread. Simple do: `.unsubscribeOn(Schedulers.io())`

**Comment by nairbspace** [comment]
Ah interesting. Yeah that's what I've been doing. 

I'd figure I mention it though because I remember a similar issue awhile back with okhttp. See [square/retrofit#1069](https://github.com/square/retrofit/issues/1069), the fix is also posted at the bottom. The stacktrace is similar, except when it goes to the okhttp-ws libraries. Since the -ws library is still experimental I'd figure there might be issues. I've only seen this happen on Samsung devices though (surprise surprise).

Other than that your library has been great! Thanks for this.
